### PR TITLE
fix volunteer opportunites component

### LINKED ISSUE #127: Fix Volunteer Opportunities component
image

The photo is too small and too far to the left

Make sure it looks good on different devices

### PR DESCRIPTION
**Pull request by shirleyduong**
iPhone: hides photo

iPad:
image

Laptop/Desktop:
image

### CODE REVIEW

File: src/components/home/VolunteerOpportunities.tsx [hunk 1]
```diff
@@ -15,10 +15,10 @@ const VolunteerOpportunities = () => {
         free to show up! We'd love all the help we can get!
       </p>
       <div className="flex w-full flex-row py-2 sm:py-10">
-        <div className="hidden items-center justify-center sm:flex">
+        <div className="hidden justify-center sm:flex md:mx-8 md:mt-24 md:h-full md:w-3/5 lg:my-10 lg:w-full">
           <Photo
             image={VolunteerPhoto}
-            width={"w-1/2 lg: w-3/4"}
+            width=""
```
Comment (SafeDuck) [inline src/components/home/VolunteerOpportunities.tsx]: Instead of having a width prop
In the `Photo` component, add a default prop for width as an empty string (so that you don't need to pass in  this prop when calling the function).

Also are you sure that you want to get rid of the width for this particular photo?

**Review by SafeDuck — CHANGES_REQUESTED** [review]

File: src/components/home/VolunteerOpportunities.tsx (hunk 1 above)
Comment (shirleyduong) [reply src/components/home/VolunteerOpportunities.tsx]: whenever I tried using width, it would make the photo smaller than I would like

**Review by SafeDuck — APPROVED** [review]
